### ISSUE TITLE
New iMac estimated age 10 years

### ISSUE THREAD

**Issue by maburdett** [univ-of-utah-marriott-library-apple/scl_jamf_extension_attribute_collection#1]
I have a new iMac Intel (Retina 5K, 27-Inch, 2019), with a serial number H12C5HM0JV3X that the estimated age come out to 10 years.

**Comment by uurazzle** [comment]
Hello @maburdett:

Thanks for the feedback. The developer of this extension attribute as looked at the code and it looks tricky. The character used for year in the serial number is designed to cycle every 10 years and it just cycled. He will see if he can get more info from the OS to figure out if we need to add 10 (or 20...) to the value and will reply back when we have time to code and test it.
